---
title: "R Notebook"
output: html_notebook
---

VERIFICATION INCOHERENCE DE DATES
```{r}
# Verif incoherence des dates ---> fin de ligne avant le début de la ligne
# ---> 2 NA car pas de dates_J0 ni date de fin de ligne thErapeutique
# ---> patients n°16 et 52, a exclure ?
# bd_traitement %>% select(n, num_ligne_ttt, date_fin_ligne_therapeutique_ttt, date_j0_ttt ) %>% mutate(duree_traitement = as.integer(date_fin_ligne_therapeutique_ttt - date_j0_ttt)) %>% filter(duree_traitement<0 | is.na(duree_traitement))

# On va transformer notre base longue en base large pour mettre les lignes les unes a la suite des autres pour verifier les coherences de dates entre chaque ligne theapeutique.

vars <- c("annee_fin","mois_fin","jour_fin","annee_j0","mois_j0","jour_j0","duree_traitement")

bd_l <- bd_traitement  %>% 
  select(n, num_ligne_ttt, date_fin_ligne_therapeutique_ttt, date_j0_ttt ) %>% 
  filter(n!=16 & n!=52) %>%
  mutate(duree_traitement = as.integer(date_fin_ligne_therapeutique_ttt - date_j0_ttt)) %>%
  mutate_at(vars(date_fin_ligne_therapeutique_ttt,date_j0_ttt), as.character) %>%
  separate(date_fin_ligne_therapeutique_ttt, into = c("annee_fin","mois_fin","jour_fin"), sep = "-") %>% 
  separate(date_j0_ttt, into = c("annee_j0","mois_j0","jour_j0"), sep = "-") %>% 
  mutate(num_ligne_ttt = case_when(
    num_ligne_ttt==1~"ligne_1",
    num_ligne_ttt==2~"ligne_2",
    num_ligne_ttt==3~"ligne_3",
    num_ligne_ttt==4~"ligne_4",
    num_ligne_ttt==5~"ligne_5",
    TRUE~"exclure"
    )) %>% 
  unite(xxx, vars, sep=" ") %>% 
  spread(num_ligne_ttt, xxx) %>% 
  separate(ligne_1, str_c(vars, "_ligne_1", sep=c(""))) %>% 
  separate(ligne_2, str_c(vars, "_ligne_2", sep=c(""))) %>%
  separate(ligne_3, str_c(vars, "_ligne_3", sep=c(""))) %>% 
  separate(ligne_4, str_c(vars, "_ligne_4", sep=c(""))) %>% 
  separate(ligne_5, str_c(vars, "_ligne_5", sep=c(""))) %>% 
  mutate(date_fin_ligne1 = str_c(annee_fin_ligne_1,mois_fin_ligne_1,jour_fin_ligne_1,sep="-"),
         date_fin_ligne2 = str_c(annee_fin_ligne_2,mois_fin_ligne_2,jour_fin_ligne_2,sep="-"),
         date_fin_ligne3 = str_c(annee_fin_ligne_3,mois_fin_ligne_3,jour_fin_ligne_3,sep="-"),
         date_fin_ligne4 = str_c(annee_fin_ligne_4,mois_fin_ligne_4,jour_fin_ligne_4,sep="-"),
         date_fin_ligne5 = str_c(annee_fin_ligne_5,mois_fin_ligne_5,jour_fin_ligne_5,sep="-"),
         date_j0_ligne1 = str_c(annee_j0_ligne_1,mois_j0_ligne_1,jour_j0_ligne_1,sep="-"),
         date_j0_ligne2 = str_c(annee_j0_ligne_2,mois_j0_ligne_2,jour_j0_ligne_2,sep="-"),
         date_j0_ligne3 = str_c(annee_j0_ligne_3,mois_j0_ligne_3,jour_j0_ligne_3,sep="-"),
         date_j0_ligne4 = str_c(annee_j0_ligne_4,mois_j0_ligne_4,jour_j0_ligne_4,sep="-"),
         date_j0_ligne5 = str_c(annee_j0_ligne_5,mois_j0_ligne_5,jour_j0_ligne_5,sep="-"))%>%
  select(n, date_j0_ligne1, date_fin_ligne1, duree_traitement_ligne_1, date_j0_ligne2, date_fin_ligne2,duree_traitement_ligne_2, date_j0_ligne3, date_fin_ligne3, duree_traitement_ligne_3, date_j0_ligne4, date_fin_ligne4,duree_traitement_ligne_4, date_j0_ligne5, date_fin_ligne5, duree_traitement_ligne_5)
# Mettre au bon format les variables de cette base de donnees
date_var <- bd_l %>% select(contains("date")) %>% colnames
duree_var <- bd_l %>% select(contains("duree")) %>% colnames 
bd_l <- bd_l  %>% mutate_at(vars(date_var), ymd) %>% mutate_at(vars(duree_var), as.integer)      
# Verifications coherence date de debut et date de fin de ligne therapeutique
bd_l <- bd_l %>% mutate(
  delai_fl1_dl1 = as.integer(date_fin_ligne1 - date_j0_ligne1),
  delai_fl1_dl2 = as.integer(date_j0_ligne2 - date_fin_ligne1),
  delai_fl2_dl3 = as.integer(date_j0_ligne3 - date_fin_ligne2),
  delai_fl3_dl4 = as.integer(date_j0_ligne4 - date_fin_ligne3),
  delai_fl4_dl5 = as.integer(date_j0_ligne5 - date_fin_ligne4)
)

# --> la seule incoherence serait :
# --> Pour le patient n°6 : la ligne 5 commence avant la fin de la ligne 4
bd_l %>% filter( 
  delai_fl1_dl1 < 0 | delai_fl1_dl2 < 0 | delai_fl2_dl3 < 0 | delai_fl3_dl4 < 0 | delai_fl4_dl5 < 0
) 

```

VERIFICATION DATES DE GESTES

```{r }
mabase %>% select(n, num_ligne_ttt, date_j0_ttt, date_fin_ligne_therapeutique_ttt, geste_1, date_geste1, geste_2, date_geste2, geste_3, date_geste3, geste_4, date_geste_4, geste_5, date_geste_5, geste_6, date_geste_6) %>% 
  filter(n==10) #%>% 
  #filter(geste_1==1 | geste_2==1 | geste_3==1 | geste_4==1 | geste_5==1 | geste_6==1 )

write.table(verif_geste,"verif_geste.csv", row.names = FALSE, sep ="*", dec=",", na=" ")
```

